@startuml 'Snack API ER diagram'

hide circle
skinparam linetype ortho

entity "Client" as client {
  **id : string <<generated>> **
  --
  name : text
  email : text
  cpf : text
}

entity "Product" as product {
  * **id : string <<generated>> **
  --
  *name : text
  *category: text
  *price: float
  *available: boolean
  *active: boolean
  description:text
  images: jsonb
}

entity "Order" as order {
  * **id : string <<generated>> **
  --
  * **clientId: string <<FK>>**
  * **paymentId: string <<FK>>**
  *commands : text
  *status: text
  *createdAt: date
}

entity "Payment" as payment {
  * **id : string <<generated>> **
  --
  *value : float
  *method: text
  *createdAt: date
}

entity "OrderProduct" as orderProduct {
  * **id : string <<generated>> **
  --
   * **orderId: string <<FK>>**
  * **productId: string <<FK>>**
}

client ||-o{ order
order ||-o| payment
order ||-|{ orderProduct
orderProduct ||-|{ product

@enduml