apiVersion: apps/v1
kind: Deployment
metadata:
  name: snack-bar-api
  namespace: snack-bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snack-bar-api
  template:
    metadata:
      labels:
        app: snack-bar-api
    spec:
      containers:
      - name: snack-bar-api
        image: deborasilveira/snack-bar-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgresql://root:root@snack-bar-db:5432/snack-api-db"
        resources:
          requests:
            cpu: 100m
